Repository Azure/aml-workspace, pull requests merged in 2020-05, with the labels that each got.

#5 Added input validation & unit tests
  .cloud/.azure/workspace.json
  .github/workflows/python.yml
  .gitignore
  Dockerfile
  code/entrypoint.sh
  code/main.py
  code/schemas.py
  code/utils.py
  tests/test_main.py
  tests/test_utils.py
Labels: enhancement

#8 Updated ReadMe
  README.md
Labels: documentation

#9 Update azureml-sdk to 1.5.0
  Dockerfile
Labels: enhancement

#13 Remove ls from entrypoint.sh
  .gitattributes
  CODE_OF_CONDUCT.md
  LICENSE
  README.md
  SECURITY.md
  code/entrypoint.sh
Labels: bug

#15 Upgrade to Azure ML SDK 1.6.0
  Dockerfile
Labels: enhancement
